### ISSUE TITLE
Failed to start the bot

### ISSUE THREAD

**Issue by dickymuliafiqri** [BianSepang/WeebProject#16]
I'm facing issue to start the bot, i have no idea to do.  
So, i bring you the log...  
  
Machine:  
- OS: Ubuntu 20.04  
- Python: 3.8.10  
  
Log:  
[1625440495-weebproject.log](https://github.com/BianSepang/WeebProject/files/6760726/1625440495-weebproject.log)

**Comment by dickymuliafiqri** [comment]
But, it seems work perfectly with your docker image....

I just compose it with postgres, and it's work.

Maybe wrong python version ???

**Comment by BianSepang** [comment]
You need at least Python 3.9 to run the bot

**Comment by dickymuliafiqri** [comment]
Yes thanks, i think it will be good if you add python version badge
